### ISSUE TITLE
[FEATURE] Support Debian based systems compliant with pep 668 (system package manager managed Python3 dependencies)

### ISSUE THREAD

**Issue by tomuk5** [akamai/uls#46]
Please review the existing `pip3 install -q -r */*/requirements.txt` commands in the scripts to either:

1. support detection of pep 668 system managed python packages and act accordingly and install these via `apt`
2. support detection of pep 668 compliant systems and use a venv accordingly using `pip`/`pipx` 
3. support detection of pep 668 compliant systems and prompt the user with a package list to install (list the dependencies for the user) and allow the user to manually meet these via their own packaging and deployment processes (ansible,etc).

```error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.```

**Comment by MikeSchiessl** [comment]
Hi @tomuk5,

sorry for the delay in my response but I've been OOO so this is the first time I have had the chance to dig into your enhancement request.

You are explicitly talking about the installer here: https://github.com/akamai/uls/blob/main/scripts/get-uls.sh ?
I fully understand the problem you're scratching here, but I have not found a genius way of solving this in an elegant way. So I did the most leanest thing I could imagine: I ask the user what he wants to do - yeah not best thing but works for me.

If you have something smarter, feel free to come up with a PR


Fixed in version v1.6.7
